### ISSUE TITLE
Use the balance as payment method

### ISSUE THREAD

**Issue by strteamservidores** [Azuriom/Plugin-Shop#157] opened 2023-09-12 12:00 UTC
Hello guys, isn't there a way to enable payment for products in the store with the account balance and using another payment method together? I enabled coins on the website but it only allows you to purchase with coins and does not allow you to use any other payment method. 
i want to use both, the balance and payment methods. 
If it's not possible, it's a good suggestion to add it to Azuriom

**Comment by MrMicky-FR** [comment] 2023-09-12 12:50
Duplicate of #106

**Closed by MrMicky-FR** 2023-09-12 12:50 UTC
Labels: duplicate
