### ISSUE TITLE
Suggestion: Paypal income modification.

### ISSUE THREAD

**Issue by MathisAudureau** [Azuriom/Plugin-Shop#60] opened 2022-05-23 17:22 UTC
My suggestion is to be able in the shop, to be able to enter several paypal email addresses to which the revenue from the server would be donated. And also be able to assign a percentage to each PayPal. (Maximum at 100%). 

This could allow some users to better manage their income directly via Azuriom.

**Comment by MrMicky-FR** [comment] 2022-05-23 17:26
Duplicate of #26

**Closed by MrMicky-FR** 2022-05-23 17:26 UTC
Labels: duplicate
