### ISSUE TITLE
Custom Balance Top-Up for Azuriom Shop

### ISSUE THREAD

**Issue by BAD7777** [Azuriom/Plugin-Shop#213] opened 2024-08-08 21:59 UTC
Enables users to top up their balance without selecting a predefined package. This plugin allows for a custom amount to be specified, offering flexibility and convenience for users.

**Comment by MrMicky-FR** [comment] 2024-08-08 22:02
Duplicate of #198

**Closed by MrMicky-FR** 2024-08-08 22:02 UTC
