### ISSUE TITLE
Option to give away items.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Plugin-Shop#102] opened 2023-01-29 19:55 UTC
Option to give away items. When the purchase is finished, it will appear if you want to give it away and if so, be able to enter the name / steam of the user.

**Comment by MrMicky-FR** [comment] 2023-01-29 20:12
Duplicate of #18 (and no need to bump, a reaction is enough)

**Closed by MrMicky-FR** 2023-01-29 20:12 UTC
