### ISSUE TITLE
Add a text box so users can enter something and this will be a variable.

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Plugin-Shop#149] opened 2023-08-11 11:19 UTC
Allow an option that allows users to put text/numbers and this is set as a variable and send it through the command line (rcon)

**Comment by MrMicky-FR** [comment] 2023-08-11 11:21
Duplicate of #53

**Closed** 2023-08-11 11:21 UTC
Labels: duplicate

**Comment by MrMicky-FR** [comment] 2023-08-11 11:23
It’s already the third time you open a duplicate issue just for the shop plugin, please make sure to check for the existing issues before opening a new one (there is 15 open issues, shouldn’t take much time), thank you 😊
