### ISSUE TITLE
[Improvement] Real Currency and/or website currency option

### ISSUE THREAD

**Issue by scarecr0w12** [Azuriom/Plugin-Shop#153] opened 2023-08-29 18:48 UTC
While it is nice to have the ability to use Either Real currency OR website currency, it would make a lot more sense, and be more functional to allow real currency AND/OR Website currency. Because there are ways to get website currency, outside of purchasing that currency, It would make FAR more sense to have an option to use either Real currency, Website currency or both.

**Comment by MrMicky-FR** [comment] 2023-08-29 18:56
Duplicate of #106

**Closed by MrMicky-FR** 2023-08-29 18:56 UTC
