### ISSUE TITLE
Gift Purchases for Azuriom Shop

### ISSUE THREAD

**Issue by BAD7777** [Azuriom/Plugin-Shop#214] opened 2024-08-08 22:00 UTC
Allows players to purchase items for another username, making it possible to buy subscriptions and other goods as gifts. A convenient feature for those who want to treat their friends or other players, as items are no longer tied to their own username.

**Comment by MrMicky-FR** [comment] 2024-08-08 22:04
Duplicate of #155

In the meantime you can use the feature to purchase giftcards so players can offer giftcards

**Closed by MrMicky-FR** 2024-08-08 22:04 UTC
