### ISSUE TITLE
Make a subscription based payment model.

### ISSUE THREAD

**Issue by MaximusMcfly** [Azuriom/Plugin-Shop#164] opened 2023-09-30 07:53 UTC

**Comment by MrMicky-FR** [comment] 2023-09-30 07:56
Duplicate of #31

**Closed by MrMicky-FR** 2023-09-30 07:56 UTC

**Comment by MrMicky-FR** [comment] 2024-03-06 09:44
Hi, for updates on shop subscriptions and how to use them see [this comment](https://github.com/Azuriom/Plugin-Shop/issues/31#issuecomment-1974868836) 🚀
