### ISSUE TITLE
Payment on pending

### ISSUE THREAD

**Issue by lauretandretheo** [Azuriom/Plugin-Shop#54] opened 2022-04-06 06:30 UTC
Hello, 
My shop plugin don't work, when I create an order and pay it with Paypal, my order stay in pending in the table shop_payments.
(Note: when I make free payment it works, and the order is in status completed)

I configured a command with Azlink on the product, and I don't receive it with paypal but I receive it with free product.

Here is my /storage/logs file : https://pastebin.com/raw/ZGYQzq6k
Here is my website : https://www.ocean-quest.fr

**Comment by MrMicky-FR** [comment] 2022-04-22 07:19
After further investigation it was caused by an issue in Laravel removing unicode characters not in UTF-8, making the PayPal request appears invalid for PayPal server.

It's been fixed with laravel/framework#42065, and will be available in the next Azuriom release

**Closed by MrMicky-FR** 2022-04-22 07:19 UTC
