### ISSUE TITLE
responsive 

### ISSUE THREAD

**Issue by LucasB25** [Azuriom/Plugin-Shop#84] opened 2022-09-28 23:34 UTC
<img width="301" alt="image" src="https://user-images.githubusercontent.com/50886682/192906502-30778b92-7de7-4c01-a1ba-fc21c2a7822d.png">
les boutons son coller

**Comment by MrMicky-FR** [comment] 2022-11-08 18:09
Closing this as duplicate of Azuriom/Azuriom#229

**Closed by MrMicky-FR** 2022-11-08 18:09 UTC
