### ISSUE TITLE
Issuing a role for a while

### ISSUE THREAD

**Issue by c0d1xd3v** [Azuriom/Plugin-Shop#97] opened 2023-01-06 09:58 UTC
When purchasing privileges, users can be assigned roles. Since some privileges are sold for a certain period, it would be nice to add the ability to remove this role and put the standard one if the user has not renewed his service.

**Comment by MrMicky-FR** [comment] 2023-01-06 10:00
Related/Duplicate of #31

**Closed by MrMicky-FR** 2023-01-06 10:00 UTC
