### ISSUE TITLE
multi-category products

### ISSUE THREAD

**Issue by AceCookiess** [Azuriom/Plugin-Shop#195] opened 2024-04-01 14:59 UTC
Add the possibility of having the same product in several categories, to avoid having to duplicate the same product in several categories.

this would save on product management and is possible with the DB

**Comment by MrMicky-FR** [comment] 2024-04-01 15:44
You already opened a duplicate issue so same answer as before... Closing as duplicate of #166

**Closed by MrMicky-FR** 2024-04-01 15:44 UTC
