### ISSUE TITLE
Access by user name

### ISSUE THREAD

**Issue by zvy5** [Azuriom/Plugin-Shop#57] opened 2022-04-21 20:04 UTC
How can I make in the CMS with the platform to Minecraft Bedrock can access and make purchases only by placing the username without having to log in through the Microsoft account. For example as in Tebex or CraftingStore.

![msedge_aaTgFPFxoZ](https://user-images.githubusercontent.com/36092786/164543553-7be00bf7-2243-4f57-8b8a-eb7e4aa91e04.png)

**Comment by MrMicky-FR** [comment] 2022-04-21 20:26
Hi, currently it's not possible to login only through username. However, it's possible to select during installation login with username/password (users will need to create an account), which can be used if your server accepts offline-mode players.

I've marked this as a suggestion, so it may be implemented later :)

**Comment by djkriss0804** [comment] 2022-12-08 17:31
Hello, I am in favor of introducing functionality with the option of manually entering the player's nickname in the purchase window for whom the package is to be purchased.
As a person running minecraft servers, in my case, I see that sometimes there are teams in which not everyone has the opportunity to buy, for example, a Rank Package, but a friend has the opportunity to buy it but there is no way to do it, the fact is there is an option to transfer the website currency for which you can buy a package between accounts but it is a bit of circumvention of functionality because sometimes someone may want to surprise fellow and buy for him a package where there was also a case that I was getting requested many time for it and as the owner of a few servers I don't see anything wrong with it but still in such situations it takes my time to do it.
You can also do it by adding a function in the shopping cart where we buy it for ourselves as a default option and for de secondary option as a gift, and when the selected option is "gift" then we needed enter the nickname for which one the package is to be purchased from the store.
It seems to me that such functionality would appeal to the owners of servers using this system and, most importantly, to the players.
But despite everything, in my opinion, you should be required to register and logged in to account to have acces to buy on such a site, because in case of problems it is easiest to find out who, when and if actually made a purchase.

**Comment by MrMicky-FR** [comment] 2022-12-23 11:43
Closing as duplicate of #18

**Closed by MrMicky-FR** 2022-12-23 11:43 UTC
Labels: enhancement
